### ISSUE TITLE
Character block for Korean input is misplaced to one space right while typing the letter

### ISSUE THREAD

**Issue by sangiye0** [BreeceW/WinUIEdit#8]
HI,

When I typing a Korean character, character block which is used for combining letters is coming after the character. So, when you edit the sentence after you write something, the character block mask the next character.

![Animation](https://github.com/user-attachments/assets/775dcc84-122e-4bbb-a441-e7fe1d5e18e4)

Normally, it should be on the character which I am typing:)

![Animation2](https://github.com/user-attachments/assets/a520fc87-005a-472c-91f2-0e7b109acb57)

**Comment by BreeceW** [comment]
Thanks for reporting this—the code that turns the block caret on is not correct. With the new IME support (TSF), the IME is supposed to tell the control what style to use for composition, so I am looking into how to retrieve and render the correct styles.
